<?php
/**
 * Its used for Client Language
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos_Lite\Libs
 */

namespace Vite_Reward_Lite\Libs;

if ( ! class_exists( __NAMESPACE__ . '\Client_Language' ) ) {
	/**
	 * Class VitePOS_API_Base
	 *
	 * @package Vite_Reward_Lite\Libs
	 */
	class Vite_Client_Language {
		/**
		 * The get Admin Languages is generated by appsbd
		 *
		 * @param mixed $kernel_object Its the object of kernel.
		 *
		 * @return mixed
		 */
		public static function get_admin_languages( &$kernel_object ) {
			$language                                = array();
			$language['Reward Points Rules']         = $kernel_object->__( 'Reward Points Rules' );
			$language['Reward Points Table']         = $kernel_object->__( 'Reward Points Table' );
			$language['Badge List']                  = $kernel_object->__( 'Badge List' );
			$language['Email Template']              = $kernel_object->__( 'Email Template' );
			$language['Settings']                    = $kernel_object->__( 'Settings' );
			$language['Reward Rules']                = $kernel_object->__( 'Reward Rules' );
			$language['Points Table']                = $kernel_object->__( 'Points Table' );
			$language['Badges']                      = $kernel_object->__( 'Badges' );
			$language['Loading Reward Rules']        = $kernel_object->__( 'Loading Reward Rules' );
			$language['Loading Points Table List']   = $kernel_object->__( 'Loading Points Table List' );
			$language['Loading Badges']              = $kernel_object->__( 'Loading Badges' );
			$language['Loading Email Template List'] = $kernel_object->__( 'Loading Email Template List' );
			$language['Loading Settings']            = $kernel_object->__( 'Loading Settings' );
			$language['Configure']                   = $kernel_object->__( 'Configure' );
			$language['Enable']                      = $kernel_object->__( 'Enable' );
			$language['Disable']                     = $kernel_object->__( 'Disable' );
			$language['Close']                       = $kernel_object->__( 'Close' );
			$language['Save']                        = $kernel_object->__( 'Save' );
			$language['Current Points']              = $kernel_object->__( 'Current Points' );
			$language['Points Value']                = $kernel_object->__( 'Points Value' );
			$language['Update points']               = $kernel_object->__( 'Update points' );
			$language['Enter Points']                = $kernel_object->__( 'Enter Points' );
			$language['Remark']                      = $kernel_object->__( 'Remark' );
			$language['Cancel']                      = $kernel_object->__( 'Cancel' );
			$language['Update']                      = $kernel_object->__( 'Update' );
			$language['Add Badge']                   = $kernel_object->__( 'Add Badge' );
			$language['Update Badge']                = $kernel_object->__( 'Update Badge' );
			$language['Edit']                        = $kernel_object->__( 'Edit' );
			$language['Delete']                      = $kernel_object->__( 'Delete' );
			$language['Badge Name']                  = $kernel_object->__( 'Badge Name' );
			$language['Enter Badge Name']            = $kernel_object->__( 'Enter Badge Name' );
			$language['Threshold Points']            = $kernel_object->__( 'Threshold Points' );
			$language['Welcome Points']              = $kernel_object->__( 'Welcome Points' );
			$language['Description']                 = $kernel_object->__( 'Description' );
			$language['Add']                         = $kernel_object->__( 'Add' );
			$language['Toggle this to show overall accumulated points on My Account page.'] = $kernel_object->__( 'Toggle this to show overall accumulated points on My Account page.' );
			$language['Show Total Earning Points']                                    = $kernel_object->__( 'Show Total Earning Points' );
			$language['Toggle this to show assigned user badges on My Account page.'] = $kernel_object->__( 'Toggle this to show assigned user badges on My Account page.' );
			$language['Show User Badges']                      = $kernel_object->__( 'Show User Badges' );
			$language['Toggle this to enable this settings.']  = $kernel_object->__( 'Toggle this to enable this settings.' );
			$language['Enable Badge']                          = $kernel_object->__( 'Enable Badge' );
			$language['Badge Settings']                        = $kernel_object->__( 'Badge Settings' );
			$language['Enable Points Notification']            = $kernel_object->__( 'Enable Points Notification' );
			$language['Enable Email Point Notification']       = $kernel_object->__( 'Enable Email Point Notification' );
			$language['Points']                                = $kernel_object->__( 'Points' );
			$language['Amount']                                = $kernel_object->__( 'Amount' );
			$language['Per Currency Points Conversion']        = $kernel_object->__( 'Per Currency Points Conversion' );
			$language['Allow per currency points conversion.'] = $kernel_object->__( 'Allow per currency points conversion.' );
			$language['Basic Settings']                        = $kernel_object->__( 'Basic Settings' );
			$language['Email Body']                            = $kernel_object->__( 'Email Body' );
			$language['Edit Email Template']                   = $kernel_object->__( 'Edit Email Template' );
			$language['Email Subject']                         = $kernel_object->__( 'Email Subject' );
			$language['Enable Currency Points Conversion']     = $kernel_object->__( 'Enable Currency Points Conversion' );

			return $language;
		}
	}
}
